# Generated by Django 5.2.11 on 2026-03-03 14:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud_proveedor', 'Solicitud de Proveedor'), ('aprobacion_proveedor', 'Aprobación de Proveedor'), ('rechazo_proveedor', 'Rechazo de Proveedor'), ('nueva_oferta', 'Nueva Oferta'), ('aprobacion_oferta', 'Aprobación de Oferta'), ('rechazo_oferta', 'Rechazo de Oferta'), ('nuevo_comentario', 'Nuevo Comentario'), ('nueva_calificacion', 'Nueva Calificación'), ('nuevo_favorito', 'Nuevo Favorito'), ('sistema', 'Notificación del Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
