# Generated by Django 5.2.11 on 2026-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
