# Generated by Django 5.2.11 on 2026-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_alter_oferta_precio_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='enlace_externo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_descuento',
            field=models.BigIntegerField(verbose_name='Precio con descuento'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_original',
            field=models.BigIntegerField(verbose_name='Precio original'),
        ),
    ]
