# Generated by Django 5.2.11 on 2026-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_alter_oferta_enlace_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio con descuento'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio original'),
        ),
    ]
