# Generated by Django 5.2.11 on 2026-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0007_alter_oferta_porcentaje_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen representativa'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
