# Generated by Django 5.2.11 on 2026-02-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('consumidor', 'Consumidor'), ('proveedor', 'Proveedor')], default='consumidor', max_length=20),
        ),
    ]
