# Generated by Django 5.2.11 on 2026-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='solicitud_proveedor',
            field=models.BooleanField(default=False),
        ),
    ]
