# Generated by Django 5.2.11 on 2026-02-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_perfil_solicitud_proveedor_perfil_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
