# Generated by Django 5.2.11 on 2026-02-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfil_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
