# Generated by Django 5.2.11 on 2026-03-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfil_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web oficial'),
        ),
    ]
