# Generated by Django 5.2.11 on 2026-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_perfil_sitio_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudproveedor',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_verificacion',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20, verbose_name='Nivel de verificación'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='descripcion_negocio',
            field=models.TextField(default=None, verbose_name='¿Qué productos o servicios ofreces?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentos_proveedores/'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='experiencia',
            field=models.TextField(blank=True, verbose_name='Experiencia en ventas'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='fotos_productos',
            field=models.FileField(blank=True, null=True, upload_to='productos_proveedores/'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='nivel_asignado',
            field=models.CharField(choices=[('basico', 'Verificación Básica'), ('intermedio', 'Verificación Intermedia'), ('avanzado', 'Verificación Avanzada')], default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='nivel_solicitado',
            field=models.CharField(choices=[('basico', 'Verificación Básica'), ('intermedio', 'Verificación Intermedia'), ('avanzado', 'Verificación Avanzada')], default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='notas_admin',
            field=models.TextField(blank=True, verbose_name='Notas del administrador'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='referencias',
            field=models.TextField(blank=True, verbose_name='Referencias comerciales'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio web o red social'),
        ),
        migrations.AddField(
            model_name='solicitudproveedor',
            name='telefono_contacto',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono de contacto'),
            preserve_default=False,
        ),
    ]
