# Generated by Django 5.2.11 on 2026-03-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_solicitudproveedor_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='visitas',
            field=models.IntegerField(default=0, verbose_name='Número de visitas'),
        ),
    ]
